x-default-policy: &default_policy
  restart: always
  networks:
    - llm-observability

services:
  app:
    <<: *default_policy
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 8501:8501
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      COHERE_API_KEY: ${COHERE_API_KEY}
      LANGFUSE_HOST: http://langfuse-server:3000
      LANGFUSE_PUBLIC_KEY: pk-1234567890
      LANGFUSE_SECRET_KEY: sk-1234567890
      LANGFUSE_RELEASE: 0.0.1-SNAPSHOT
    volumes:
      - ./app/docs:/app/docs
    develop:
      watch:
        - action: sync
          path: ./app/
          target: /app
        - action: rebuild
          path: ./app/

  langfuse-server:
    <<: *default_policy
    container_name: langfuse
    image: langfuse/langfuse:2.82.0
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - NEXTAUTH_SECRET=mysecret
      - SALT=mysalt
      - ENCRYPTION_KEY=a277a2912fbbc0aabbfe6eac95b597ae03ffe30477bb388e8d32d7b010e89875 # generate via `openssl rand -hex 32`
      - NEXTAUTH_URL=http://localhost:3000
      - TELEMETRY_ENABLED=${TELEMETRY_ENABLED:-true}
      - LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES=${LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES:-false}
      - LANGFUSE_INIT_ORG_ID=org-123456789
      - LANGFUSE_INIT_ORG_NAME=tech-book-fest-17-llm-o11y
      - LANGFUSE_INIT_PROJECT_ID=pj-1234567890
      - LANGFUSE_INIT_PROJECT_NAME=Ask the BigBaBy
      - LANGFUSE_INIT_PROJECT_PUBLIC_KEY=pk-1234567890
      - LANGFUSE_INIT_PROJECT_SECRET_KEY=sk-1234567890
      - LANGFUSE_INIT_USER_EMAIL=user@example.com
      - LANGFUSE_INIT_USER_NAME=guest
      - LANGFUSE_INIT_USER_PASSWORD=password

  db:
    <<: *default_policy
    container_name: postgresql
    image: postgres:17
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - database_data:/var/lib/postgresql/data

  jupyter:
    <<: *default_policy
    container_name: jupyter
    image: jupyter/base-notebook:python-3.11
    ports:
      - 8080:8080
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./requirements.txt:/home/jovyan/requirements.txt
      - ./app/docs:/home/jovyan/docs
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.disable_check_xsrf=True --port=8080 --notebook-dir=/home/jovyan/work
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      COHERE_API_KEY: ${COHERE_API_KEY}
      JUPYTER_ENABLE_LAB: yes
      LANGFUSE_HOST: http://langfuse-server:3000
      LANGFUSE_PUBLIC_KEY: pk-1234567890
      LANGFUSE_SECRET_KEY: sk-1234567890

networks:
  llm-observability:

volumes:
  database_data:
    driver: local
